context:
  version: "0.6.11"

package:
  name: castxml
  version: ${{ version }}

source:
  url: https://github.com/CastXML/CastXML/archive/refs/tags/v${{ version }}.tar.gz
  sha256: fc5b49f802b67f98ecea10564bc171c660020836a48cecefc416681a2d2e1d3d

build:
  number: 0
  script:
    - cmake -GNinja -S . -B build ${{ "$CMAKE_ARGS" if unix else "%CMAKE_ARGS%" }}
    - cmake --build build
    - ${{ "if %errorlevel% neq 0 exit 1" if win }}
    - cmake --install build
    - ${{ "if %errorlevel% neq 0 exit 1" if win }}

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - ninja
  host:
    - clangdev 20.1.*
    - libclang-cpp
    - libllvm20
    # zlib is a transitive dependency of llvmdev and not needed
    - zlib

  ignore_run_exports:
    from_package:
      # looks like on Windows, libzlib _is_ linked
      - ${{ "zlib" if unix }}


tests:
  - script:
      - castxml --version

  - script:
      - if: unix
        then:
          - castxml --castxml-cc-gnu $CXX --castxml-gccxml -o test.xml test.cpp
        else:
          - castxml --castxml-cc-msvc %CXX% --castxml-gccxml -o test.xml test.cpp
          - if %errorlevel% neq 0 exit 1

    files:
      recipe:
        - test.cpp

    requirements:
      run:
        - ${{ compiler('cxx') }}

about:
  homepage: https://github.com/CastXML/CastXML
  license: Apache-2.0
  license_file: LICENSE
  summary: C-family Abstract Syntax Tree XML Output

extra:
  recipe-maintainers:
    - wolfv
